language: "ko-KR"
reviews:
  profile: chill
  high_level_summary: true
  high_level_summary_placeholder: true
  review_status: true
  auto_review:
    enabled: true
    drafts: false
    base_branches: ["*"]
  tools:
    eslint:
      enabled: true
    gitleaks:
      enabled: true