language: 'ko-KR'

reviews:
  profile: chill
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: false
  review_status: true
  auto_review:
    enabled: true

    skip_bot_prs: false

    drafts: false
    base_branches:
      - 'main'
      - 'develop'

  tools:
    eslint:
      enabled: true
    gitleaks:
      enabled: true
